import type { Metadata } from 'next';
import { Chakra_Petch, JetBrains_Mono, Inter } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/components/AuthProvider';
import { Toaster } from 'sonner';

const chakraPetch = Chakra_Petch({
    subsets: ['latin'],
    weight: ['400', '600', '700'],
    variable: '--font-display',
});

const jetbrainsMono = JetBrains_Mono({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    variable: '--font-mono',
});

const inter = Inter({
    subsets: ['latin'],
    weight: ['400', '500'],
    variable: '--font-sans',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            lang="de"
            className={`${chakraPetch.variable} ${jetbrainsMono.variable} ${inter.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                {/* Sonner Toaster für robuste Next.js App-Router Performance */}
                <Toaster
                    theme="dark"
                    position="top-right"
                    closeButton
                    toastOptions={{
                        unstyled: true,
                        classNames: {
                            toast: 'font-mono text-xs bg-panel border border-line text-text px-4 py-3 shadow-panel flex items-center gap-3 [clip-path:polygon(10px_0,100%_0,100%_calc(100%-10px),calc(100%-10px)_100%,0_100%,0_10px)]',
                            title: 'text-text',
                            description: 'text-text-dim',
                            success: '!border-cyan-dim',
                            error: '!border-danger/40',
                            closeButton:
                                '!bg-panel-alt !border-line !text-text-dim hover:!text-text',
                        },
                    }}
                />
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
