import type { Metadata } from 'next';
import { Chakra_Petch, JetBrains_Mono, Inter } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/components/AuthProvider';
import { Toaster } from 'sonner';

const chakraPetch = Chakra_Petch({
    subsets: ['latin'],
    weight: ['400', '600', '700'],
    variable: '--font-display',
});

const jetbrainsMono = JetBrains_Mono({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    variable: '--font-mono',
});

const inter = Inter({
    subsets: ['latin'],
    weight: ['400', '500'],
    variable: '--font-sans',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            lang="de"
            className={`${chakraPetch.variable} ${jetbrainsMono.variable} ${inter.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                {/* Sonner Toaster für robuste Next.js App-Router Performance */}
                <Toaster theme="dark" position="bottom-right" closeButton richColors />
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
